# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeerViewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeerViewer
  pod 'Alamofire', '~> 5.2'
    
  target 'BeerViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeerViewerUITests' do
    # Pods for testing
  end

end
